### ISSUE TITLE
Consider using the LSST's Docker containers

### ISSUE THREAD

**Issue by jrmullaney** [lsst-uk/obs_vista#1]
Hi Raphael,

I was going to email you, but then thought it may be better to communicate here so that everything's in one place.

I've just read the thread you started on the LSST community forum. If you're going to be working with the weekly builds, you may be better off working with LSST's Docker containers, if you aren't already doing so. This way, you won't have to reinstall every week.

We started with using the lsstsw installation, but moved over to using Docker containers about 2 years ago. It's much easier for local development.

Happy to share my Dockerfile to help you get set up, if you like.

J

**Comment by raphaelshirley** [comment]
Hi James,

Ok, I have used Docker before but not with weekly updates. That might help me install on the HPC which I'm currently struggling with. I'll look into it thanks. I was panicking a little bit thinking about reinstalling lsstsw every week so that sounds helpful.

Raphael.

**Comment by jrmullaney** [comment]
If you're trying to install on IRIS, then this may help. It's from some documentation I wrote last year for LSST:UK:

> The LSST Data Management (DM) team have provided three different of ways of installing the LSST pipeline. We have already mentioned the Docker-based installation, which is by far the quickest and most straightforward way to deploy the LSST pipeline on a standalone machine, and still allows a user to utilise their own local obs_package. The two other methods are: 
> via the “newinstall.sh” script; 
> with lsstsw and lsst-build. 
> We chose the former for installation, as the newinstall.sh script checks to determine whether downloadable prebuilt binaries exist for your operating system. If they do, this provides a quicker means of installing the LSST pipeline that also avoids the need to install various prerequisite software (which is beneficial when installing on a system where one does not have root priveleges). IRIS (DiRAC [www.dirac.ac.uk]) uses resources typically run Scientific Linux, which is a flavour of Linux based on Red  Hat Enterprise Linux. Binaries of the LSST pipeline are currently being built for Red  Hat Enterprise Linux, and we found that newinstall.sh was able to use these to install the LSST pipeline on IRIS. 
> We installed the LSST pipeline within the bash shell (which is the default shell on IRIS) by following the instructions online (https://pipelines.lsst.io/install/newinstall.html#newinstall-find-binaries). Since we were able to use the prebuilt binaries, we were able to skip the “Prerequistes” step and move straight to Step  2:  “Make an Installation Directory”. We made an install directory within our own user area on IRIS (i.e.that is, /home/username/lsst_stack) and downloaded and ran the newinstall.sh bash script within that directory (with the –ct option set to ensure it checked-for and used prebuilt binaries). We recognise, however, that this may not be a suitable option should we wish the pipeline to be used by multiple different users simultaneously.  
> After loading the LSST software environment in our shell, we used the EUPS versioning system (which was installed by the newinstall.sh script) to install version 18.1.0 of the LSST Science Pipeline. Full install of the LSST stack on IRIS using the newinstall.sh method took of the order 30 minutes. 
> To utilise the installed LSST Pipeline on IRIS, we set up the LSST software environment in every new shell by sourcing the loadlsst.bash script that was installed in the aforementioned lsst_stack directory. Doing this allows us to set up a specified obs_package which, in turn, provides access to all the LSST Pipeline command-line tasks (i.e., executables) and sets up the Python environment giving access to the LSST Pipeline’s Python modules.

**Comment by raphaelshirley** [comment]
Hi,

I managed the newinstall.sh method but not the lsstsw method so I can work on the obs_vista package. I actually think it may simply be that I ran out of home space as we may be limited to 40Gb and the lsstsw install on my mac is around 45Gb. Does using Docker reduce the space needed?

Cheers,

Raphael.

**Comment by jrmullaney** [comment]
Despite what I say in my tutorial, you don't actually need the lsstsw method to develop your own obs package (I realised this later). My Docker image is 7GB, so quite a lot smaller.

**Comment by raphaelshirley** [comment]
Great I was juggling my files around to accommodate lsstsw. I'll start using Docker or at least the normal lsst newinstall installation. Do you have a file which pulls the latest version every week then or does Docker handle that for you?

Thanks very much!

R.

**Comment by jrmullaney** [comment]
You can get the latest weekly builds by using the w_latest tag:
docker pull lsstsqre/centos:7-stack-lsst_distrib-w_latest
See: https://pipelines.lsst.io/install/docker.html#docker-tags

I guess you could make a cron job if you wanted to build it weekly without fail, but it's probably better that you do it manually so you've got more control. You probably don't want to be using the container when it automatically re-builds.

I'll make a GitHub repo and put my Dockerfile etc in it, as there are some tweaks I've made to get things to work properly. I've also made a Docker image from which you can call a Jupiter notebook that has access to the LSST installation, which is really useful for checking outputs.

**Comment by raphaelshirley** [comment]
Great, I was just about to ask about Jupyter notebooks... I have the docker build locally so will try to setup the obs_vista package tomorrow. I'm still not sure how to do that without the lsstsw installation where you have access to the packages folder structure but I'm sure I'll figure it out.

**Comment by jrmullaney** [comment]
I've put the files I use to build and run the docker images and containers in:
https://github.com/jrmullaney/lsstDocker

Wrt. setting up the obs_vista package, all you need to do is launch the docker container with a `-volume` that points from your local obs package to a directory where the stack code is kept within the docker container. Take a look at `standard/runLsstDocker.sh` in the above repository for more details.

**Comment by raphaelshirley** [comment]
Great, thanks very much for that. I'll try to set it up this week.
